apiVersion: v1
kind: Secret
metadata:
  name: wordpress-conf
  namespace: wp
stringData:
  WORDPRESS_DB_HOST: cluster1-haproxy.db.svc.cluster.local
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: <password>
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_TABLE_PREFIX: wp_
  WORDPRESS_AUTH_KEY: <auth_key>
  WORDPRESS_SECURE_AUTH_KEY: <secure_auth_key>
  WORDPRESS_LOGGED_IN_KEY: <logged_in_key>
  WORDPRESS_NONCE_KEY: <nonce_key>
  WORDPRESS_AUTH_SALT: <auth_salt>
  WORDPRESS_SECURE_AUTH_SALT: <secure_auth_salt>
  WORDPRESS_LOGGED_IN_SALT: <logged_in_salt>
  WORDPRESS_NONCE_SALT: <nonce_salt>
  WP_REDIS_CLIENT: "predis"
  WP_REDIS_SCHEME: "unix"
  WP_REDIS_PATH: "/var/run/redis/redis.sock"
  WP_REDIS_SERVERS: "['tcp://redis-leader:6379?database=5&role=master', 'tcp://localhost:6379?database=5&alias=replica-01']"
