apiVersion: v1
kind: Secret
metadata:
  name: wordpress-conf
  namespace: wp
stringData:
  WORDPRESS_DB_HOST: cluster1-haproxy.db.svc.cluster.local
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: <password>
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_TABLE_PREFIX: wp_
