apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/v1.17.0/deploy/bundle.yaml
  - https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/v1.17.0/deploy/cr.yaml
